config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pokemons#index'
  resources :users, only: [:show, :edit, :update]

# お気に入り
  resources :pokemons do
    resource :favorites, only: [:create, :destroy]
  end

# ポケモンにコメント
  resources :pokemons do 
    resources :comments, only: [:create, :destroy]
  end

# フレンド
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end

  #Good 
  resources :comments do
    resources :goods, only: [:create, :destroy]
  end

  # Bad
  resources :comments do
    resources :bads, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bad.rb
class Bad < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/comment.rb
class Comment < ApplicationRecord

  belongs_to :pokemon
  belongs_to :user

  has_many :goods
  has_many :bads
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :pokemon
  
end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  validates :order, presence: true
  validates :name, presence: true
  validates :image_url, presence: true

  belongs_to :user
  has_many :favorites

  has_many :comments

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable

  has_many :pokemons
  has_many :favorites

  has_many :favorite_pokemons, through: :favorites, source: :pokemon
  mount_uploader :image, ImageUploader

  has_many :comments


  # フォローする側から見てされる側を集める
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  # フォローされる側から見てフォローしてくる人を集める
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(user)
    passive_relationships.find_by(following_id: user.id).present?
  end
  

  # Good and Bad
  has_many :goods
  has_many :bads
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :image])
  end
end

app/controllers/bads_controller.rb
class BadsController < ApplicationController

  before_action :set_variables
  
  def create
    bad = current_user.bads.build(comment_id: params[:comment_id])
    bad.save
  end

  def destroy
    bad = Bad.find_by(comment_id: params[:comment_id], user_id: current_user.id)
    bad.destroy
  end


  private
  def set_variables
    @comment = Comment.find(params[:comment_id])
    @id_name = "#bad-link-#{@comment.id}"
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    pokemon = Pokemon.find(params[:pokemon_id])
    @comment = Comment.create(comment_params)
    @comment.user_id = current_user.id
    
    redirect_back(fallback_location: '/pokemons/#{pokemon.id}')
  end

  def destroy
    Comment.find(params[:id]).destroy
    redirect_back(fallback_location: '/pokemons/#{pokemon.id}')
  end
  
  
  private
  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, pokemon_id: params[:pokemon_id])
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_variables

  def create
    favorite = current_user.favorites.build(pokemon_id: params[:pokemon_id])
    favorite.save
  end

  def destroy
    favorite = Favorite.find_by(pokemon_id: params[:pokemon_id], user_id: current_user.id)
    favorite.destroy
  end



  private

  def set_variables
    @pokemon = Pokemon.find(params[:pokemon_id])
    @id_name = "#like-link-#{@pokemon.id}"
  end
  
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
before_action :set_variables

  def create
    good = current_user.goods.build(comment_id: params[:comment_id])
    good.save
  end

  def destroy
    good = Good.find_by(comment_id: params[:comment_id], user_id: current_user.id)
    good.destroy
  end

  private
  def set_variables
    @comment = Comment.find(params[:comment_id])
    @id_name = "#like-link-#{@comment.id}"
  end
  
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :move_to_index, except: [:index]

  def index
    # fav_count = Pokemon.joins(:favorites).group(:pokemon_id).count
    # fav_ids = Hash[fav_count.sort_by{ | k, v | v}].keys
    # @pokemons = Pokemon.where(id: fav_ids).includes(:user)
    @pokemons = Pokemon.all.order(id: "DESC").includes(:user)

  end

  def show
    @pokemon = Pokemon.find(params[:id])
    @comment = Comment.new
    @comments = @pokemon.comments
  end
  
  def new
    return if params[:search].blank?
    raw_response = Faraday.get "https://pokeapi.co/api/v2/pokemon/#{params[:search]}"
    text_response = Faraday.get "https://pokeapi.co/api/v2/pokemon-species/#{params[:search]}/"

    if raw_response.status == 200
      # ポケモンがあったら
      response = JSON.parse(raw_response.body)
      textres = JSON.parse(text_response.body)

      @pokemon = Pokemon.new(order: response['id'], 
        name: response['name'], image_url: response["sprites"]["front_default"], 
          type1: response['types'][0]['type']['name'],
            description: textres['flavor_text_entries'][1]['flavor_text'])

    else
      # なければ
      redirect_to new_pokemon_path, notice: "#{raw_response.status}エラー！"
    end
  end


  def create
    @pokemon = Pokemon.new(pokemon_params)
    if @pokemon.save
      redirect_to pokemons_path, notice: "You caught a #{@pokemon.name} !!"
    else
      render :new
    end
  end


  def destroy
    pokemon = Pokemon.find(params[:id])
    pokemon.destroy
    redirect_to "/users/#{current_user.id}"
  end
  

  private
  def pokemon_params
    params.require(:pokemon).permit(:order, :name, :image_url, :type1, :description).merge(user_id: current_user.id)
  end
  def move_to_index
    redirect_to action: :index unless user_signed_in?
  end
  
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @nickname = @user.nickname
    @userimage = @user.image.url
    @userinfo = @user.created_at
    @pokemons = @user.pokemons
    @fav_pokemons = @user.favorite_pokemons

    @follow_user= User.find(params[:id])
    @f_user = @follow_user.followings
    @ed_user = @follow_user.followers
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end
  
  def follows
    user = User.find(params[:id])
    @users = user.followings
  end
  def followers
    user = User.find(params[:id])
    @users = user.followers
  end
  


  private

  def user_params
    params.require(:user).permit(:nickname, :email, :image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bads_helper.rb
module BadsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bads/_badicon.html.erb
<%= link_to comment_bads_path(comment.id), method: :post, remote: true do %>
    <i class="samll material-icons" style="margin-left: 10px;">thumb_down</i>
<% end %>
<p style="margin-left: 5px;"><%= comment.bads.count %></p>

app/views/bads/create.html.erb
<h1>Bads#create</h1>
<p>Find me in app/views/bads/create.html.erb</p>

app/views/bads/create.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render partial: 'bads/badicon', locals: {comment: @comment}) %>');

app/views/bads/destroy.html.erb
<h1>Bads#destroy</h1>
<p>Find me in app/views/bads/destroy.html.erb</p>

app/views/favorites/_favorite.html.erb
<% if user_signed_in? %>
            <% if pokemon.favorited_by?(current_user) %>
            <!-- ログインしているユーザーがファボしたかどうかで分岐 -->
            <div class="fav-icons">
              <%= link_to pokemon_favorites_path(pokemon.id), method: :delete, remote: true  do %>
                <i class="samll material-icons">thumb_up</i>
              <% end %>
                <p><%= pokemon.favorites.count %></p>
            </div>

            <% else %>

            <div class="not-fav">
            <%=link_to pokemon_favorites_path(pokemon.id), method: :post, remote: true  do %>
              <i class="samll material-icons">thumb_up</i>
            <% end %>
              <p><%= pokemon.favorites.count %></p>
            </div>
            <% end %>
            <% else %>
            <p><span>Number of favorites: </span><%= pokemon.favorites.count %></p>
            <% end %>

app/views/favorites/create.html.erb
<h1>Favorites#create</h1>
<p>Find me in app/views/favorites/create.html.erb</p>

app/views/favorites/create.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render partial: 'favorites/favorite', locals: {pokemon: @pokemon}) %>');

app/views/favorites/destroy.html.erb
<h1>Favorites#destroy</h1>
<p>Find me in app/views/favorites/destroy.html.erb</p>

app/views/favorites/destroy.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render partial: 'favorites/favorite', locals: {pokemon: @pokemon}) %>');

app/views/goods/_goodicon.html.erb
  <%= link_to comment_goods_path(comment.id), method: :post, remote: true  do %>
    <i class="samll material-icons">thumb_up</i>
  <% end %>
  <p style="margin-left: 5px;"><%= comment.goods.count %></p>

app/views/goods/create.html.erb
<h1>Goods#create</h1>
<p>Find me in app/views/goods/create.html.erb</p>

app/views/goods/create.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render partial: 'goods/goodicon', locals: {comment: @comment}) %>');

app/views/goods/destroy.html.erb
<h1>Goods#destroy</h1>
<p>Find me in app/views/goods/destroy.html.erb</p>

app/views/goods/destroy.js.erb
$("<%= @id_name %>").html('<%= escape_javascript(render partial: 'goods/goodicon', locals: {comment: @comment}) %>');

app/views/pokemons/destroy.html.erb
<div>
  <h1>you have released pokemon👋👋👋</h1>
  <%= link_to 'HOME', root_path %>
</div>

app/views/pokemons/index.html.erb
<div class="mainimages">
  <%= image_tag 'main.jpeg', style: "height: 700px; width: 100%" %>
  <a href="new_user_registration_path">
    <h1>Let's Start !!</h1>
  </a>
</div>

<div class="container">
  <div class="row maintext">
    <h2 class="col s12 center-align">Catch and Share </h2>
    <div class="row center-align icons">
      <div class="col s4">
        <i class="large material-icons">search</i>
        <h5>search your Pokemons</h5>
      </div>
      <div class="col s4">
        <i class="large material-icons">add_box</i>
        <h5>add pokemons</h5>
      </div>
      <div class="col s4">
        <i class="large material-icons">mood</i>
        <h5>collect and share your memories </h5>
      </div>
    </div>

    <div class="col s12 center-align" style="margin-bottom: 50px;">
      <%= render "shared/search", { path: new_pokemon_path } %>
    </div>

    <div class="row">
      <div class="col s12 center-align pokemaintext">
        <h3>Pokemons that all member cought</h3>
      </div>
    </div>
    
    <div class="poketeble">
      <table>
        <tr>
          <th></th>
          <th>No</th>
          <th>Name</th>
          <th>Trainer</th>
          <th>Favorite</th>
          <th>Detail</th>
        </tr>
        <% if @pokemons.present? %>
        <% @pokemons.each do |pokemon| %>
        <tr>
          <td><%= image_tag(pokemon.image_url, size: "150") %></td>
          <td><%= pokemon.order %></td>
          <td><%= pokemon.name %></td>
          <td><a href="/users/<%= pokemon.user.id %>">
              <%= pokemon.user.nickname %>
            </a></td>

          <td class="center-align" id="like-link-<%= pokemon.id %>">
            <%= render partial: 'favorites/favorite', locals: {pokemon: pokemon} %>
          </td>

            <td><%= link_to 'Details', "/pokemons/#{pokemon.id}", {method: :get} %></td>
        </tr>
        <% end %>
        <% end %>
      </table>
      </div>

    </div>
</div>

app/views/pokemons/new.html.erb
<div class="container">
  <div class="row">
    <div class="col s12 newmaintext">
      <h3 class="center-align">catch pokemons</h3>
    </div>
  </div>

  <div class="card">
    <div class="card-content white-text">
      <span class="card-title center-align">Directions for use</span>
      <p class="center-align">Enter any number from 0 to 800 ;)</p>
      <p class="center-align">If the pokemon that you encounted is your favorite one, let's get it !!</p>
    </div>
  </div>  

  <div class="search center-align">
    <%= render "shared/search", { path: new_pokemon_path } %>
  </div>

  <div class="poketeble">
      <table>
        <tr>
          <th></th>
          <th>No</th>
          <th>Name</th>
          <th>Type</th>
          <th>Flavor text</th>
        </tr>
        <% if @pokemon.present? %>
        <tr>
          <td><%= image_tag(@pokemon.image_url, size: "200") %></td>
          <td><%= @pokemon.order %></td>
          <td><%= @pokemon.name %></td>
          <td><%= @pokemon.type1 %></td>
          <td class="pokedes"><%= @pokemon.description %></td>
        </tr>
        <% end %>
      </table>

      <div class="center-align searchbtn">
        <% if @pokemon.present? %>
          <%= form_with model: @pokemon, local: true do |f| %>
            <%= f.hidden_field :order %>
            <%= f.hidden_field :name %>
            <%= f.hidden_field :image_url %>
            <%= f.hidden_field :type1 %>
            <%= f.hidden_field :description %>
            <a class="waves-effect waves-light btn-large btn-flat" style="margin-top: 30px"><%= f.submit 'GET!!', name: nil %></a>
          <% end %>
        <% end %>
      </div>

      <div class="footer"></div>
  </div>
</div>

app/views/pokemons/show.html.erb
<div class="container">
  <div class="poketeble">
      <table>
        <tr>
          <th></th>
          <th>No</th>
          <th>Name</th>
          <th>Type</th>
          <th>Trainer</th>
          <th>Favorite</th>
          <% if current_user.id == @pokemon.user.id %>
          <th>Rlease</th>
          <% end %>
        </tr>
        <% if @pokemon.present? %>
        <tr>
          <td><%= image_tag(@pokemon.image_url, size: "200") %></td>
          <td><%= @pokemon.order %></td>
          <td><%= @pokemon.name %></td>
          <td><%= @pokemon.type1 %></td>
          <td><a href="/users/<%= @pokemon.user.id %>">
              <%= @pokemon.user.nickname %>
            </a></td>

          <td class="center-align" id="like-link-<%= @pokemon.id %>">
            <%= render partial: 'favorites/favorite', locals: {pokemon: @pokemon} %>
          </td>

<%# 削除ボタン %>
            <div class="release-btn">
              <% if current_user.id == @pokemon.user.id %>
                <td><%= link_to "/pokemons/#{@pokemon.id}", method: :delete do %>
                  <i class="samll material-icons">mood_bad</i>
                <% end %>
              <% end %>
              </td>
            </div>
            
        </tr>
        <% end %>
      </table>
  </div>

<%# ポケモンテキスト %>
  <div class="desc">
    <% if @pokemon.present? %>
    <div class="card">
      <div class="card-content white-text">
        <span class="card-title center-align">Flaver text</span>
        <p class="center-align"><%= @pokemon.description %></p>
      </div>
    </div>
    <% end %>
  </div>

<%# コメントフォーム %>
<div class="comment-area">
    <div class="col s8">
      <div class=" input-field comment_form center-align">
        <% if current_user %>
          <div class="row">
            <%= form_with(model: [@pokemon, @comment], local: true) do |form| %>
              <div class="col s6">
                <%= form.text_area :text, placeholder: "Comment", class: "materialize-textarea"%>
              </div>
              <div class="col s2">
              <a class="waves-effect waves-light btn-small btn-flat comment-btn" 
                style="margin-left: -50px; background-color: #F8CD9E;"><%= form.submit 'send'%></a>
              </div>
            <% end %>
            </div>
          <% else %>
            <p>ログインが必要です</p>
          </div>
          <% end %>
      </div>
    </div>
</div>


<%# コメント %>
  <div class="row">
    <div class="col s12">
      <% if @comments %>
        <% @comments.each do |comment| %>
        <div class="card comment_card">

          <div class="card-content comment_name">
            <%= image_tag comment.user.image.url, size: "50"%>
            <a href="/users/<%= comment.user.id %>" style="border: none; margin-top: 18px; margin-left: 10px;">
              <p><%= comment.user.nickname %></p>
            </a>

            <div class="good-bad">
              <div id="like-link-<%= comment.id%>" style="display: flex">
                <%= render partial: 'goods/goodicon', locals: {comment: comment} %>
              </div>     
              <div id="bad-link-<%= comment.id%>" style="display: flex">
                <%= render partial: 'bads/badicon', locals: {comment: comment} %>
              </div>
            </div>

          </div>
          

          <div class="card-content comment_text">
            <div class="comment-text">
              <p><%= comment.text %></p>
              
            </div>
            <div class="deleteicon">
            <%=link_to "/pokemons/#{@pokemon.id}/comments/#{comment.id}", method: :delete do %>
              <i class="samll material-icons">delete</i>
            <% end %>
            </div>
          </div>
        </div>
        <% end %>
      <% end %>
    </div>
  </div>
  
  <div class="footer">
  </div>

</div>

app/views/users/edit.html.erb
<div class="container" style="width: 40%; margin-top: 100px;">
  <div class="edit-title">
    <h5>Edit your info</h5>
  </div>

<%= form_with model: current_user, class: :form, local: true do |form| %>
  <div class="input-field col s6">
    <%= form.text_field :nickname, class: :form__title %>
  </div>
  <div class="input-field col s6">
    <%= form.text_field :email, class: :form__text %>
  </div>

  <div style="display: flex;">
    <%= form.file_field :image %>
    <%= image_tag(current_user.image.url, size: "100") %>
  </div>
  <br>
  <button class="btn waves-effect waves-light" type="submit" name="action" style="background-color: #FB9D7E; color: white;"><%= form.submit 'Update', class: :form__btn %>
    <i class="material-icons right">send</i>
  </button>
<% end %>
</div>

app/views/users/followers.html.erb
<div class="container">

    <div class="center-align" style="color: #F8CD9E;">
        <h3>Follower</h3>
    </div>

    <% @users.each do |user| %>
        <div class="col s4">
            <div class="card f-card">
                <div class="card-content f-content">
                    <%= image_tag user.image.url, size: "70"%>
                    <a href="/users/<%= user.id %>" style="border: none;">
                        <p><%= user.nickname %></p>
                    </a>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/users/follows.html.erb
<div class="container">

    <div class="center-align" style="color: #F8CD9E;">
        <h3>Follows</h3>
    </div>

    <% @users.each do |user| %>
        <div class="col s4">
            <div class="card f-card">
                <div class="card-content f-content">
                    <%= image_tag user.image.url, size: "70"%>
                    <a href="/users/<%= user.id %>" style="border: none;">
                        <p><%= user.nickname %></p>
                    </a>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <%# プロフィールカード %>
    <div class="col s12 center-align">
      <h2 class="header profile_header"><%= @nickname %>'s' profile</h2>
      <div class="card horizontal card2">
        <div class="card-image">
          <%= image_tag @userimage, size: "200"%>
        </div>
        <div class="card-stacked">
          <div class="card-content userinfo">
            <p><%= @nickname %></p>
            <div class="follow-count" class="follow">
              <p style="margin-right: 30px;"><%= link_to "Follow:", follows_user_path(@follow_user.id) %>
                <b><%= @f_user.count %></b></p>
              <p><%= link_to "Follower:", followers_user_path(@follow_user.id) %> <b><%= @ed_user.count %></b></p>
            </div>

            <% if @user.followed_by?(current_user) %>
              <%=link_to user_relationships_path(@user.id), method: :delete do %>
              <button class="btn-flat waves-effect waves-light followbtn" type="submit">Following
                <i class="material-icons right">person</i>
              </button>
              <% end %>
            <% elsif @user.id == current_user.id %>
            <% else %>
              <%=link_to user_relationships_path(@user.id), method: :post do %>
              <button class="btn-flat waves-effect waves-light followbtn" type="submit">Follow
                <i class="material-icons right">person_add</i>
              </button>
              <% end %>
            <% end %>

            <% if current_user.id == @user.id %>
            <br><br>
              <%= link_to 'Edit user info', edit_user_path(current_user) %>
            <% end %>
          </div>
        </div>
      </div>
    </div>

    <%# 所持ポケモン一覧 %>
    <div class="col s12 havepokemons">
      <h5><%= @nickname %>'s pokemon</h5>
      <div class="col s12 havepokemon card card3">
        <% @pokemons.each do |pokemon|  %>
        <div class="card-content">
          <%= link_to "/pokemons/#{pokemon.id}"  do %>
          <%= image_tag(pokemon.image_url, size: "150") %>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>

    <%# お気に入り一覧 %>
    <div class="col s12 havepokemons">
      <h5>favorite's pokemon</h5>
      <div class="col s12 havepokemon card card3">
        <% @fav_pokemons.each do |pokemon|  %>
        <div class="card-content">
          <%= link_to "/pokemons/#{pokemon.id}"  do %>
          <%= image_tag(pokemon.image_url, size: "150") %>
          <% end %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="footer">
  </div>
</div>